### ISSUE TITLE
Support multiple uploads

### ISSUE THREAD

**Issue by JoshuaEstes** [JoshuaEstes/sfPluploadPlugin#1]
Currently only works for uploading one file, need to add support for uploading multiple files for saving in the database

**Comment by robo47** [comment]
From my point of View multiple uploads work with the Widget, setting max_file_count to > 1, but I did not use your controller + action only the widget and only html5 since I need the stuff in a backend with authentication and that seems to not work that easy with flash

**Comment by JoshuaEstes** [comment]
Yeah, multiple uploads will work, but the issue that I didn't have time to work on was how are you able to keep track of that once the user submits a form? Right now there is just some simple js that places the uploaded filename in a hidden field. I don't think it would be to hard to update the field to be an array so when the user submits the form, you get an array of files they uploaded.

**Comment by robo47** [comment]
What do you wan't to do ? or why would you want to get an array of the uploaded files ?

Do you want to make asynchron uploads via plupload AND then fill a hidden field (or multiple ones) with what it has successfully transfered and then submit the "rest" of your form ?

I didn't, to many additional requirements for that, if somebody closes the page you are still left with the uploaded files lying around and adds additional requirements like a cronjob or integration into the uploadscript itself which (regularly) checks the temp-upload-dir for unused uploads and chunks if canceled uploads.

Plupload has support for additional data to the request.
So as long as you don't use chunking!! [Means you are limit by phps limits of post-size and upload-size], there is one upload-request per file (in the background). So if each upload is some kind of object and you have all needed informations for the object in the form (no additional upload-fields!), you can just add them to the request and make that one request create the object.

I currently have plupload embedded only in forms whichs aim is to create multiple "objects". 
For example I want to create multiple Images in a gallery. 
So I have an extra page with a form which includes plupload and a select-box where i choose the category of the gallery. 
Some additional javascript together with pluploads multipart_params adds the category-field to the post-request send from plupload, since I don't use chunks, each upload-request is complete (tested with runtime flash,html5,silverlight in multiple browsers and on Win and Linux) including the file AND the category.

That allows me to use a normal sfForm, make the uploader itself ignored via an sfValidatorPass-Validator, use a normal symfony-based upload-validator for the field "file".
The upload-validator does some magic for me behind the scenes:
- Naming the file like i wan't it (I don't like symfony1 way of creating a new name based on a hash)
- Append a number if a collission would happen (uploads which are images can land in 2 different directories, a mistake I made a long time ago, but can't just fix across multiple projects)

Then I take care of creating the object in the database.

That saves me from making it to complex.

First problem so far was to modify symfonys session-handling to work with the flash-runtime. (Since I need flash as fallback for all uses using old browsers, especially internet explorer).

The problem with flash is, it does not send cookies (variations across versions from Flash 8 to 11, which send wrong cookies (IE-cookies on all other browsers), over sending some, to including the cookies as post-vars in the request), so if you are using it in a secured backend, all requests using the flash runtime will be cookieless, therefor symfony can't determine a user and auth and you get a 401 header and no upload happens. [Just to mention it, the "headers" setting of plupload does not work with flash, at least in current stable version of flash on linux and windows]

Will probably blog about that solution the next days if I find some time to clean up my current solution, which does not support all features of plupload (no chunking) and I have yet to write the code to nicely handle upload-errors based on validation-problems. i already return json containing the errors the form-validator gives, but have to show them to the user, so he knows why uploads failed (not only an error-sign and http-error). Because for example the file is of a not allowed type.

And I have to add a least some basic i18n since I need that Stuff mostly in german.

**Comment by JoshuaEstes** [comment]
I'd be interested in reading your article about it. What I started using it for was to create a client portal where users can upload files. Each page would contain various information about the upload such as name, description, etc. So in my case I only needed to be able to allow a user to upload one file.

In the future I will introduce a page that allows a user to upload multiple files, then fill in the info for each object.

I tried to make this so it could be used for both. I'd like to tackle the issue when I have more time to dedicate to this.
